---
- id: 52
  title: C57BL/6N
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: 
  contributor_id: 
  policy_id: 2023
  uuid: 
  first_letter: 
- id: 53
  title: C57/BL6N
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: 
  contributor_id: 
  policy_id: 2024
  uuid: 
  first_letter: 
- id: 54
  title: default
  organism_id: 887518578
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: true
  contributor_type: 
  contributor_id: 
  policy_id: 2025
  uuid: 
  first_letter: 
- id: 55
  title: new strain
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: 
  contributor_id: 
  policy_id: 2026
  uuid: 
  first_letter: 
- id: 56
  title: BL6/N
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: 
  contributor_id: 
  policy_id: 2027
  uuid: 
  first_letter: 
- id: 57
  title: default
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: true
  contributor_type: User
  contributor_id: 308
  policy_id: 2028
  uuid: 
  first_letter: 
- id: 58
  title: Teststrain
  organism_id: 614935680
  parent_id: 
  synonym: Test2
  comment: ''
  provider_id: ''
  provider_name: ''
  is_dummy: false
  contributor_type: User
  contributor_id: 2
  policy_id: 2029
  uuid: 
  first_letter: 
- id: 60
  title: C57BL/6
  organism_id: 448538968
  parent_id: 
  synonym: ''
  comment: ''
  provider_id: '29'
  provider_name: Gülce Gülcüler
  is_dummy: false
  contributor_type: User
  contributor_id: 430
  policy_id: 2221
  uuid: 
  first_letter: 
- id: 61
  title: C57/BL6J
  organism_id: 448538968
  parent_id: 55
  synonym: ''
  comment: ''
  provider_id: ''
  provider_name: ''
  is_dummy: false
  contributor_type: User
  contributor_id: 365
  policy_id: 2388
  uuid: 
  first_letter: 
- id: 62
  title: Sprague-Dawley rat
  organism_id: 614935680
  parent_id: 
  synonym: ''
  comment: high reproduction rate and low incidence of spontaneous tumor.
  provider_id: '9'
  provider_name: ''
  is_dummy: false
  contributor_type: User
  contributor_id: 430
  policy_id: 2487
  uuid: 98dcdd78-df33-4ea9-bc19-b3d7b6b9f2d2
  first_letter: 
- id: 63
  title: default
  organism_id: 614935680
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: true
  contributor_type: User
  contributor_id: 231
  policy_id: 2696
  uuid: e97ce313-b7c0-4c98-b53a-9eff10081172
  first_letter: 
- id: 65
  title: C57BL/6X
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: User
  contributor_id: 2
  policy_id: 2925
  uuid: 31605151-678d-477c-b2ca-7f764e21a574
  first_letter: 
- id: 73
  title: APC loxP (neo)
  organism_id: 448538968
  parent_id: 
  synonym: APC flox
  comment: transgene for loxP sites + neomycin casette in APC gene
  provider_id: ''
  provider_name: MEZ Leipzig
  is_dummy: false
  contributor_type: User
  contributor_id: 259
  policy_id: 3211
  uuid: 1e3201ed-5fda-4f8e-80ee-964c0b96c266
  first_letter: 
- id: 74
  title: C57BL/6J
  organism_id: 448538968
  parent_id: 
  synonym: 
  comment: 
  provider_id: 
  provider_name: 
  is_dummy: false
  contributor_type: User
  contributor_id: 363
  policy_id: 3219
  uuid: 87f5447d-e3d9-4507-920f-f35d47cefc1e
  first_letter: C
